<?php
/**
 * WordPress configuration for WASI/SQLite builds.
 * Generated by examples/wazero-wordpress/setup.sh — do not commit.
 *
 * The sqlite-database-integration plugin intercepts $wpdb calls via
 * wp-content/db.php. No MySQL connection is made; all data lives in
 * data/database/.ht.sqlite, which the Go host mounts at /data/database/
 * inside the WASM sandbox (separate from the docroot at /srv/app).
 */

// --- Database (SQLite via drop-in; the values below are unused placeholders) ---
define( 'DB_NAME',     'wordpress' );
define( 'DB_USER',     'root' );
define( 'DB_PASSWORD', '' );
define( 'DB_HOST',     'localhost' );
define( 'DB_CHARSET',  'utf8' );
define( 'DB_COLLATE',  '' );

// Absolute WASI path for the SQLite database directory.
// data/ is mounted at /data by the Go host; this must be defined BEFORE
// wp-settings.php loads the db.php drop-in so the plugin uses our path.
if ( ! defined( 'DB_DIR' ) ) {
    define( 'DB_DIR', '/data/database/' );
}

// --- Auth keys and salts ---
define( 'AUTH_KEY',         '5387da4c9f9bc823cdfd73b9e8ab17275d4e008bdcdcd2394b3c34e13befa53d' );
define( 'SECURE_AUTH_KEY',  '4e6607f8840595600492d640bd33bb3a24d55d6522a75f2ba95fe3ee9b8bfae9' );
define( 'LOGGED_IN_KEY',    'f6aca32e15bcd0532f811d5583c0ec88fca276d9a14801a7e2240b5f663ca817' );
define( 'NONCE_KEY',        'df4ea1844beb668a12c0065c2a97c0fa84693724e21b086e62dfa98bbc65fc81' );
define( 'AUTH_SALT',        '6fe5b50e50be407d87f54d53aa08e8bea90791dfb09d3aed892fe2f8b32d2f25' );
define( 'SECURE_AUTH_SALT', 'b6eae31eeafdeff3f36fef5b1aebdb2a25e90b0f19db156303174185bbe62403' );
define( 'LOGGED_IN_SALT',   'd929dc92d0eb67f51308ea95a7ad35008273072b8c39ffa1dfaaba7858624092' );
define( 'NONCE_SALT',       '4b26807664998ace9f7fd97ad2169ec2e32b1b20ce94fb9bc7f1f7d5496a0df6' );

// --- Table prefix ---
$table_prefix = 'wp_';

// --- WASI-safe settings ---

// Disable wp-cron (no outbound HTTP from WASI). Trigger /wp-cron.php from the
// host instead: */1 * * * * curl -s http://localhost:8080/wp-cron.php?doing_wp_cron
define( 'DISABLE_WP_CRON', true );

// No plugin/theme auto-updates — WASI has no outbound network.
define( 'AUTOMATIC_UPDATER_DISABLED', true );

// Block outbound HTTP requests (curl/fsockopen not available in WASI Preview1).
define( 'WP_HTTP_BLOCK_EXTERNAL', true );

// Direct filesystem access (no FTP/SSH).
define( 'FS_METHOD', 'direct' );

// Site URLs — update if running on a non-localhost address.
define( 'WP_HOME',    'http://localhost:8080' );
define( 'WP_SITEURL', 'http://localhost:8080' );

// Set to true to enable wp-admin's debug bar and error display.
define( 'WP_DEBUG',         false );
define( 'WP_DEBUG_LOG',     false );
define( 'WP_DEBUG_DISPLAY', false );

// --- Absolute path ---
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

require_once ABSPATH . 'wp-settings.php';
