#!/usr/bin/env bash
# Assemble a WordPress asset bundle for the Gimpel wordpress-honeypot module and
# (optionally) push it to an OCI registry as ghcr.io/<owner>/wordpress-assets:<wp>.
#
# The bundle is a tar of a ready-to-run WordPress docroot (core + the SQLite
# drop-in + a WASI-compat mu-plugin + a Gimpel-specific wp-config.php). Gimpel
# mounts it read-only at /app, so ALL writable paths are redirected to the
# module's writable /data mount:
#   - SQLite DB -> /data/database   (DB_DIR)
#   - uploads   -> /data/uploads    (upload_dir filter)
# Sessions/tmp use the module's ephemeral /tmp mount.
#
# Usage:
#   scripts/assemble-wordpress-assets.sh [--push]
#   WP_VERSION=6.7 scripts/assemble-wordpress-assets.sh --push
#
# Env: WP_VERSION, SQLITE_PLUGIN_VERSION, REGISTRY (default ghcr.io),
#      GITHUB_REPOSITORY_OWNER (required for --push), GITHUB_TOKEN.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

WP_VERSION="${WP_VERSION:-6.7}"
SQLITE_PLUGIN_VERSION="${SQLITE_PLUGIN_VERSION:-2.1.13}"
REGISTRY="${REGISTRY:-ghcr.io}"
REPO_OWNER="${GITHUB_REPOSITORY_OWNER:-}"
PUSH=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --push) PUSH=1; shift ;;
    *) echo "ERROR: unknown option: $1" >&2; exit 1 ;;
  esac
done

for c in curl unzip tar; do
  command -v "$c" &>/dev/null || { echo "ERROR: '$c' not found" >&2; exit 1; }
done

OUT_DIR="${REPO_ROOT}/out"
BUILD_DIR="$(mktemp -d)"
WWW="${BUILD_DIR}/www"
CACHE_DIR="${HOME}/.cache/php-wasm"
mkdir -p "${OUT_DIR}" "${CACHE_DIR}"
trap 'rm -rf "${BUILD_DIR}"' EXIT

info() { echo "==> $*"; }

# --- WordPress core ---------------------------------------------------------- #
info "Downloading WordPress ${WP_VERSION}"
WP_TARBALL="${CACHE_DIR}/wordpress-${WP_VERSION}.tar.gz"
[[ -f "${WP_TARBALL}" ]] || curl -fsSL -o "${WP_TARBALL}" "https://wordpress.org/wordpress-${WP_VERSION}.tar.gz"
tar -xzf "${WP_TARBALL}" -C "${BUILD_DIR}"
mv "${BUILD_DIR}/wordpress" "${WWW}"

# --- SQLite database integration plugin + drop-in ---------------------------- #
info "Installing sqlite-database-integration ${SQLITE_PLUGIN_VERSION}"
PLUGINS_DIR="${WWW}/wp-content/plugins"
SQLITE_ZIP="${CACHE_DIR}/sqlite-database-integration.${SQLITE_PLUGIN_VERSION}.zip"
[[ -f "${SQLITE_ZIP}" ]] || curl -fsSL -o "${SQLITE_ZIP}" \
  "https://downloads.wordpress.org/plugin/sqlite-database-integration.${SQLITE_PLUGIN_VERSION}.zip"
mkdir -p "${PLUGINS_DIR}"
unzip -q "${SQLITE_ZIP}" -d "${PLUGINS_DIR}"

DB_COPY="${PLUGINS_DIR}/sqlite-database-integration/db.copy"
DB_PHP="${WWW}/wp-content/db.php"
[[ -f "${DB_COPY}" ]] || { echo "ERROR: db.copy missing from sqlite plugin" >&2; exit 1; }
cp "${DB_COPY}" "${DB_PHP}"
sed -i "s|{SQLITE_IMPLEMENTATION_FOLDER_NAME}|sqlite-database-integration|g" "${DB_PHP}"
sed -i "s|{SQLITE_FOLDER}|database/|g" "${DB_PHP}"

# --- mu-plugins: WASI network shim + writable-path redirect ------------------ #
MU_DIR="${WWW}/wp-content/mu-plugins"
mkdir -p "${MU_DIR}"

cat > "${MU_DIR}/wasi-compat.php" << 'MUPLUGIN'
<?php
/**
 * WASI compatibility shim (must-use plugin).
 * WASI Preview1 has no sockets, so short-circuit WordPress's outbound HTTP:
 * fake a 200 for loopback (so the installer enables pretty permalinks) and
 * return a clear WP_Error for everything else instead of a fatal crash.
 */
add_filter( 'pre_http_request', static function ( $preempt, $args, $url ) {
    if ( false !== $preempt ) {
        return $preempt;
    }
    if ( preg_match( '#^https?://(localhost|127\.0\.0\.1)(:\d+)?(/|$)#', $url ) ) {
        return [
            'headers'       => [],
            'body'          => '',
            'response'      => [ 'code' => 200, 'message' => 'OK' ],
            'cookies'       => [],
            'http_response' => null,
        ];
    }
    return new WP_Error( 'http_request_failed', 'WASI Preview1: no outbound network sockets.' );
}, 10, 3 );
MUPLUGIN

cat > "${MU_DIR}/gimpel-writable-paths.php" << 'MUPLUGIN'
<?php
/**
 * Gimpel writable-path redirect (must-use plugin).
 * The docroot (/app) is mounted read-only, so send WordPress's uploads to the
 * module's writable /data mount. The SQLite DB is already redirected via DB_DIR
 * in wp-config.php.
 */
add_filter( 'upload_dir', static function ( $dirs ) {
    $base = '/data/uploads';
    $sub  = isset( $dirs['subdir'] ) ? $dirs['subdir'] : '';
    $dirs['basedir'] = $base;
    $dirs['path']    = $base . $sub;
    return $dirs;
}, 10, 1 );
MUPLUGIN

# --- Gimpel wp-config.php ----------------------------------------------------- #
info "Generating wp-config.php"
gen_salt() { head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'; }
cat > "${WWW}/wp-config.php" << PHP
<?php
/**
 * WordPress configuration for the Gimpel wordpress-honeypot module (WASI/SQLite).
 * Generated by scripts/assemble-wordpress-assets.sh. The docroot is read-only;
 * all writable state lives under the module's /data mount.
 */
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'root' );
define( 'DB_PASSWORD', '' );
define( 'DB_HOST', 'localhost' );
define( 'DB_CHARSET', 'utf8' );
define( 'DB_COLLATE', '' );

// SQLite database directory on the writable /data mount.
if ( ! defined( 'DB_DIR' ) ) {
    define( 'DB_DIR', '/data/database/' );
}

define( 'AUTH_KEY',         '$(gen_salt)' );
define( 'SECURE_AUTH_KEY',  '$(gen_salt)' );
define( 'LOGGED_IN_KEY',    '$(gen_salt)' );
define( 'NONCE_KEY',        '$(gen_salt)' );
define( 'AUTH_SALT',        '$(gen_salt)' );
define( 'SECURE_AUTH_SALT', '$(gen_salt)' );
define( 'LOGGED_IN_SALT',   '$(gen_salt)' );
define( 'NONCE_SALT',       '$(gen_salt)' );

\$table_prefix = 'wp_';

define( 'DISABLE_WP_CRON', true );
define( 'AUTOMATIC_UPDATER_DISABLED', true );
define( 'WP_HTTP_BLOCK_EXTERNAL', true );
define( 'FS_METHOD', 'direct' );
define( 'WP_DEBUG', false );

if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}
require_once ABSPATH . 'wp-settings.php';
PHP

# --- Tar the docroot so it untars with index.php at the mount root ----------- #
TAR_OUT="${OUT_DIR}/wordpress-assets-${WP_VERSION}.tar"
info "Writing ${TAR_OUT}"
tar --format=ustar --sort=name --mtime='@0' --owner=0 --group=0 --numeric-owner \
  -cf "${TAR_OUT}" -C "${WWW}" .
echo "    $(du -h "${TAR_OUT}" | cut -f1)  ${TAR_OUT}"

# --- Optional OCI push ------------------------------------------------------- #
if [[ "${PUSH}" -eq 1 ]]; then
  command -v oras &>/dev/null || { echo "ERROR: oras not found" >&2; exit 1; }
  [[ -n "${REPO_OWNER}" ]] || { echo "ERROR: GITHUB_REPOSITORY_OWNER not set" >&2; exit 1; }
  OWNER_LC="$(echo "${REPO_OWNER}" | tr '[:upper:]' '[:lower:]')"
  IMAGE_BASE="${REGISTRY}/${OWNER_LC}/wordpress-assets"
  IMAGE_REF="${IMAGE_BASE}:${WP_VERSION}"
  info "Pushing ${IMAGE_REF}"
  ( cd "${OUT_DIR}" && oras push "${IMAGE_REF}" \
      --artifact-type "application/vnd.gimpel.assets.v1" \
      --annotation "org.opencontainers.image.source=https://github.com/${REPO_OWNER}/php-wasm" \
      --annotation "gimpel.wordpress.version=${WP_VERSION}" \
      "$(basename "${TAR_OUT}"):application/vnd.gimpel.assets.tar" )
  oras tag "${IMAGE_REF}" "${IMAGE_BASE}:latest" 2>/dev/null || true
  echo "    pushed ${IMAGE_REF}"
fi

info "Done."
